//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FanDescription
    {
        public long ProductId { get; set; }
        public short AirFlow { get; set; }
        public decimal PowerMin { get; set; }
        public decimal PowerMax { get; set; }
        public short OperatingVoltageMin { get; set; }
        public short OperatingVoltageMax { get; set; }
        public short FanSpeedMin { get; set; }
        public short FanSpeedMax { get; set; }
        public byte NumOfFanSpeed { get; set; }
        public byte SoundAtMaxSpeed { get; set; }
        public decimal FanSweepDiameter { get; set; }
        public decimal HeightMin { get; set; }
        public decimal HeightMax { get; set; }
        public decimal Weight { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
