//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.FanDescriptions = new HashSet<FanDescription>();
            this.ToasterDescriptions = new HashSet<ToasterDescription>();
            this.VacuumDescriptions = new HashSet<VacuumDescription>();
        }
    
        public long ProductId { get; set; }
        public string ProductName { get; set; }
        public int ModelTypeId { get; set; }
        public int ModelId { get; set; }
        public int SubCategoryId { get; set; }
    
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FanDescription> FanDescriptions { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToasterDescription> ToasterDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacuumDescription> VacuumDescriptions { get; set; }
    }
}
