//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductId { get; set; }
        public string ProductName { get; set; }
        public int ModelTypeId { get; set; }
        public int ModelId { get; set; }
        public int SubCategoryId { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual ModelType ModelType { get; set; }
        public virtual ProductTechSpec ProductTechSpec { get; set; }
        public virtual ProductSubCategory ProductSubCategory { get; set; }
    }
}
