//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTechSpec
    {
        public long ProductId { get; set; }
        public Nullable<short> AirFlow { get; set; }
        public Nullable<decimal> PowerMin { get; set; }
        public Nullable<decimal> PowerMax { get; set; }
        public Nullable<short> OperatingVoltageMin { get; set; }
        public Nullable<short> OperatingVoltageMax { get; set; }
        public Nullable<short> FanSpeedMin { get; set; }
        public Nullable<short> FanSpeedMax { get; set; }
        public Nullable<byte> NumOfFanSpeed { get; set; }
        public Nullable<byte> SoundAtMaxSpeed { get; set; }
        public Nullable<decimal> FanSweepDiameter { get; set; }
        public Nullable<decimal> HeightMin { get; set; }
        public Nullable<decimal> HeightMax { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<byte> LevelOfSuction { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<short> MaxRuntime { get; set; }
        public Nullable<byte> LevelOfTemperature { get; set; }
        public Nullable<decimal> Length { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
