//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecFilter
    {
        public int SubCategoryId { get; set; }
        public string PropertyName { get; set; }
        public int MIN { get; set; }
        public int MAX { get; set; }
    
        public virtual ProductSubCategory ProductSubCategory { get; set; }
    }
}
