//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToasterTypeDetail
    {
        public int ModelTypeId { get; set; }
        public string UseType { get; set; }
        public string Application { get; set; }
        public string Accessories { get; set; }
        public short ModelYear { get; set; }
        public int ModelId { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
