//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerceMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacuumDescription
    {
        public long ProductId { get; set; }
        public short AirFlow { get; set; }
        public decimal PowerMin { get; set; }
        public decimal PowerMax { get; set; }
        public short OperatingVoltageMin { get; set; }
        public short OperatingVoltageMax { get; set; }
        public byte NumOfSuction { get; set; }
        public byte SoundAtMaxPower { get; set; }
        public short MaxRuntime { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
